/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CompanyFooter: typeof import('./src/components/CompanyFooter.vue')['default']
    DarkModeCard: typeof import('./src/components/DarkModeCard.vue')['default']
    DFMCard: typeof import('./src/components/DFMCard.vue')['default']
    FabCard: typeof import('./src/components/FabCard.vue')['default']
    FeatureFunctions: typeof import('./src/components/FeatureFunctions.vue')['default']
    HeaderBackground: typeof import('./src/components/HeaderBackground.vue')['default']
    HeaderBar: typeof import('./src/components/HeaderBar.vue')['default']
    HeaderBarMenu: typeof import('./src/components/HeaderBarMenu.vue')['default']
    LibraryCard: typeof import('./src/components/LibraryCard.vue')['default']
    PluginCard: typeof import('./src/components/PluginCard.vue')['default']
    RecentBlogs: typeof import('./src/components/RecentBlogs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VideoPlayerDialog: typeof import('./src/components/VideoPlayerDialog.vue')['default']
  }
}
